"""
datadog_store_integration.py
============================
Bridge between Datadog connector and OrgGPT's vector store.

⚠️ **NOTE: This file is primarily for TESTING and DEMONSTRATION purposes.**

For PRODUCTION ingestion, use `index_builder.py` instead:
  - python index_builder.py datadog_poc       # POC mode (no API keys)
  - python index_builder.py datadog_catalog   # Production mode (with API keys)
  - python index_builder.py datadog_slo       # SLO production mode

This file is used by:
  ✅ test_datadog_catalog.py  - Catalog integration demos
  ✅ test_datadog_slo.py      - SLO integration demos
  ✅ Quick prototyping and experimentation

Use cases:
  1. Testing Datadog integration without full pipeline
  2. Demos and presentations (executable test scripts)
  3. Quick prototyping of new ingestion methods
  4. Exploring API responses interactively

Responsible for:
  1. Orchestrating document ingestion (Catalog Entities, SLOs)
  2. Managing cache and TTL
  3. Async sync capabilities
"""

import logging
import hashlib
from typing import List, Optional, Dict, Any
from datetime import datetime, timedelta
from .datadog_connector import DatadogConnector

logger = logging.getLogger(__name__)


class DatadogVectorStoreIntegration:
    """
    Manages ingestion of Datadog data into OrgGPT's vector store.
    Handles caching, TTL, and incremental updates.
    
    Supports multiple data sources:
      - Catalog Entities (services, teams, applications)
      - SLOs (Service Level Objectives)
      - SLO Corrections (maintenance windows)
    """
    
    def __init__(self, vector_store, cache_ttl_seconds: int = 3600):
        """
        Args:
            vector_store: VectorStore instance from vector_store.store
            cache_ttl_seconds: Time-to-live for cached documents
        """
        self.vector_store = vector_store
        self.cache_ttl = timedelta(seconds=cache_ttl_seconds)
        self._ingestion_history: Dict[str, Any] = {}
    
    def ingest_datadog_data(self) -> Dict[str, Any]:
        """
        Extract Datadog data and ingest into vector store.
        
        Returns:
            Ingestion metadata (counts, timestamps, etc.)
        """
        logger.info("Starting Datadog data ingestion (Catalog Entity API)...")
        
        try:
            # Extract data from Datadog Catalog Entity API 
            connector = DatadogConnector()
            entities = connector.extract_catalog_entities()
            
            if not entities:
                logger.warning(" No catalog entities extracted from Datadog")
                return {"status": "no_data", "entity_count": 0}
            
            # Transform entities to RAG-ready documents
            docs = connector.catalog_transformer.transform_entities_batch(entities)
            
            if not docs:
                logger.warning(" No documents generated from entities")
                return {"status": "no_data", "document_count": 0}
            
            # Transform documents to embeddings and add to store
            metadata_list = []
            
            for i, doc in enumerate(docs):
                doc_id = self._generate_doc_id(doc)
                metadata = {
                    "source": "datadog_catalog_entity",  # Updated to Catalog Entity
                    "ingested_at": datetime.now().isoformat(),
                    "doc_index": i,
                }
                
                # Add to vector store
                # Note: VectorStore.add expects: ids, texts, embeddings, metadatas
                # Embeddings are typically generated by the embedder before calling add()
                self.vector_store.add(
                    ids=[doc_id],
                    texts=[doc],
                    embeddings=None,  # Will be generated by the store or caller
                    metadata=[metadata],
                )
                
                metadata_list.append(metadata)
            
            # Record ingestion history
            ingestion_record = {
                "timestamp": datetime.now(),
                "entity_count": len(entities),
                "document_count": len(docs),
                "status": "success",
                "metadata": metadata_list[:5],  # Store first 5 for reference
            }
            
            self._ingestion_history["last_successful"] = ingestion_record
            
            logger.info(f"Ingested {len(entities)} Catalog Entities ({len(docs)} documents) into vector store")
            
            return {
                "status": "success",
                "entity_count": len(entities),
                "document_count": len(docs),
                "ingestion_time": datetime.now().isoformat(),
            }
        
        except Exception as e:
            logger.error(f"Error during ingestion: {e}", exc_info=True)
            return {"status": "error", "error": str(e)}
    
    def ingest_slo_data(
        self,
        json_file_path: Optional[str] = None,
        include_corrections: bool = False,
    ) -> Dict[str, Any]:
        """
        Extract SLO data and ingest into vector store.
        
        Args:
            json_file_path: Optional path to JSON file (POC mode). If None, uses API.
            include_corrections: Whether to also ingest SLO corrections
        
        Returns:
            Ingestion metadata (counts, timestamps, etc.)
            
        Example:
            # From JSON file (POC mode)
            result = integration.ingest_slo_data(json_file_path="sample_get_slo_list.json")
            
            # From API (production mode)
            result = integration.ingest_slo_data(include_corrections=True)
        """
        logger.info("Starting SLO data ingestion...")
        
        try:
            # Extract data from Datadog SLO API or JSON file
            if json_file_path:
                # POC mode: Load from JSON
                connector = DatadogConnector(poc_mode=True)
                slos = connector.extract_slos_from_json(json_file_path)
            else:
                # Production mode: Use API
                connector = DatadogConnector()
                slos = connector.extract_slos()
            
            if not slos:
                logger.warning(" No SLOs extracted from Datadog")
                return {"status": "no_data", "slo_count": 0}
            
            # Transform SLOs to RAG-ready documents
            docs = connector.slo_transformer.transform_slos_batch(slos)
            
            if not docs:
                logger.warning(" No documents generated from SLOs")
                return {"status": "no_data", "document_count": 0}
            
            # Add to vector store
            metadata_list = []
            
            for i, doc in enumerate(docs):
                doc_id = self._generate_doc_id(doc, prefix="slo")
                metadata = {
                    "source": "datadog_slo",
                    "ingested_at": datetime.now().isoformat(),
                    "doc_index": i,
                }
                
                self.vector_store.add(
                    ids=[doc_id],
                    texts=[doc],
                    embeddings=None,  # Will be generated by the store
                    metadata=[metadata],
                )
                
                metadata_list.append(metadata)
            
            # Optionally ingest corrections
            correction_count = 0
            if include_corrections and not json_file_path:
                try:
                    corrections = connector.extract_slo_corrections()
                    correction_docs = connector.slo_transformer.transform_corrections_batch(corrections)
                    
                    for i, doc in enumerate(correction_docs):
                        doc_id = self._generate_doc_id(doc, prefix="slo_correction")
                        metadata = {
                            "source": "datadog_slo_correction",
                            "ingested_at": datetime.now().isoformat(),
                            "doc_index": i,
                        }
                        
                        self.vector_store.add(
                            ids=[doc_id],
                            texts=[doc],
                            embeddings=None,
                            metadata=[metadata],
                        )
                    
                    correction_count = len(correction_docs)
                    logger.info(f"Ingested {correction_count} SLO corrections")
                except Exception as e:
                    logger.warning(f" Could not ingest SLO corrections: {e}")
            
            # Record ingestion history
            ingestion_record = {
                "timestamp": datetime.now(),
                "slo_count": len(slos),
                "document_count": len(docs),
                "correction_count": correction_count,
                "status": "success",
                "metadata": metadata_list[:5],  # Store first 5 for reference
            }
            
            self._ingestion_history["last_successful_slo"] = ingestion_record
            
            logger.info(f"Ingested {len(slos)} SLOs ({len(docs)} documents) into vector store")
            
            return {
                "status": "success",
                "slo_count": len(slos),
                "document_count": len(docs),
                "correction_count": correction_count,
                "ingestion_time": datetime.now().isoformat(),
            }
        
        except Exception as e:
            logger.error(f"Error during SLO ingestion: {e}", exc_info=True)
            return {"status": "error", "error": str(e)}
    
    def ingest_all_datadog_sources(
        self,
        include_catalog: bool = True,
        include_slos: bool = True,
        slo_json_path: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Ingest all available Datadog data sources.
        
        Args:
            include_catalog: Whether to ingest Catalog Entities
            include_slos: Whether to ingest SLOs
            slo_json_path: Optional JSON file for SLO POC mode
        
        Returns:
            Combined ingestion results
        """
        results = {
            "timestamp": datetime.now().isoformat(),
            "sources": {},
        }
        
        if include_catalog:
            try:
                catalog_result = self.ingest_datadog_data()
                results["sources"]["catalog_entities"] = catalog_result
            except Exception as e:
                logger.error(f"Failed to ingest Catalog Entities: {e}")
                results["sources"]["catalog_entities"] = {"status": "error", "error": str(e)}
        
        if include_slos:
            try:
                slo_result = self.ingest_slo_data(json_file_path=slo_json_path)
                results["sources"]["slos"] = slo_result
            except Exception as e:
                logger.error(f"Failed to ingest SLOs: {e}")
                results["sources"]["slos"] = {"status": "error", "error": str(e)}
        
        # Calculate totals
        total_docs = 0
        for source_result in results["sources"].values():
            if source_result.get("status") == "success":
                total_docs += source_result.get("document_count", 0)
        
        results["total_documents"] = total_docs
        results["overall_status"] = "success" if total_docs > 0 else "partial_failure"
        
        logger.info(f"Ingestion complete: {total_docs} total documents from {len(results['sources'])} sources")
        
        return results
    
    def _generate_doc_id(self, doc: str, prefix: str = "datadog") -> str:
        """Generate unique ID for a document."""
        hash_obj = hashlib.md5(doc.encode())
        return f"{prefix}_{hash_obj.hexdigest()[:12]}"
    
    def should_refresh(self) -> bool:
        """Check if cached data should be refreshed based on TTL."""
        last_sync = self._ingestion_history.get("last_successful", {}).get("timestamp")
        
        if not last_sync:
            return True
        
        return datetime.now() - last_sync > self.cache_ttl
    
    def get_ingestion_status(self) -> Dict[str, Any]:
        """Get current ingestion status and metadata."""
        last = self._ingestion_history.get("last_successful")
        
        if not last:
            return {"status": "never_ingested"}
        
        return {
            "status": "ingested",
            "last_ingestion_time": last.get("timestamp").isoformat(),
            "document_count": last.get("document_count"),
            "needs_refresh": self.should_refresh(),
        }
