"""
datadog_store_integration.py
============================
Bridge between Datadog connector and OrgGPT's vector store.

Responsible for:
  1. Orchestrating document ingestion
  2. Managing cache and TTL
  3. Async sync capabilities
"""

import logging
import hashlib
from typing import List, Optional, Dict, Any
from datetime import datetime, timedelta
from .datadog_connector import DatadogConnector

logger = logging.getLogger(__name__)


class DatadogVectorStoreIntegration:
    """
    Manages ingestion of Datadog data into OrgGPT's vector store.
    Handles caching, TTL, and incremental updates.
    """
    
    def __init__(self, vector_store, cache_ttl_seconds: int = 3600):
        """
        Args:
            vector_store: VectorStore instance from vector_store.store
            cache_ttl_seconds: Time-to-live for cached documents
        """
        self.vector_store = vector_store
        self.cache_ttl = timedelta(seconds=cache_ttl_seconds)
        self._ingestion_history: Dict[str, Any] = {}
    
    def ingest_datadog_data(self) -> Dict[str, Any]:
        """
        Extract Datadog data and ingest into vector store.
        
        Returns:
            Ingestion metadata (counts, timestamps, etc.)
        """
        logger.info("🔄 Starting Datadog data ingestion (Catalog Entity API)...")
        
        try:
            # Extract data from Datadog Catalog Entity API ✨
            connector = DatadogConnector()
            entities = connector.extract_catalog_entities()
            
            if not entities:
                logger.warning("⚠️  No catalog entities extracted from Datadog")
                return {"status": "no_data", "entity_count": 0}
            
            # Transform entities to RAG-ready documents
            docs = connector.catalog_transformer.transform_entities_batch(entities)
            
            if not docs:
                logger.warning("⚠️  No documents generated from entities")
                return {"status": "no_data", "document_count": 0}
            
            # Transform documents to embeddings and add to store
            metadata_list = []
            
            for i, doc in enumerate(docs):
                doc_id = self._generate_doc_id(doc)
                metadata = {
                    "source": "datadog_catalog_entity",  # ✨ Updated to Catalog Entity
                    "ingested_at": datetime.now().isoformat(),
                    "doc_index": i,
                }
                
                # Add to vector store
                # Note: VectorStore.add expects: ids, texts, embeddings, metadatas
                # Embeddings are typically generated by the embedder before calling add()
                self.vector_store.add(
                    ids=[doc_id],
                    texts=[doc],
                    embeddings=None,  # Will be generated by the store or caller
                    metadata=[metadata],
                )
                
                metadata_list.append(metadata)
            
            # Record ingestion history
            ingestion_record = {
                "timestamp": datetime.now(),
                "entity_count": len(entities),
                "document_count": len(docs),
                "status": "success",
                "metadata": metadata_list[:5],  # Store first 5 for reference
            }
            
            self._ingestion_history["last_successful"] = ingestion_record
            
            logger.info(f"✅ Ingested {len(entities)} Catalog Entities ({len(docs)} documents) into vector store")
            
            return {
                "status": "success",
                "entity_count": len(entities),
                "document_count": len(docs),
                "ingestion_time": datetime.now().isoformat(),
            }
        
        except Exception as e:
            logger.error(f"❌ Error during ingestion: {e}", exc_info=True)
            return {"status": "error", "error": str(e)}
    
    def _generate_doc_id(self, doc: str) -> str:
        """Generate unique ID for a document."""
        hash_obj = hashlib.md5(doc.encode())
        return f"datadog_{hash_obj.hexdigest()[:12]}"
    
    def should_refresh(self) -> bool:
        """Check if cached data should be refreshed based on TTL."""
        last_sync = self._ingestion_history.get("last_successful", {}).get("timestamp")
        
        if not last_sync:
            return True
        
        return datetime.now() - last_sync > self.cache_ttl
    
    def get_ingestion_status(self) -> Dict[str, Any]:
        """Get current ingestion status and metadata."""
        last = self._ingestion_history.get("last_successful")
        
        if not last:
            return {"status": "never_ingested"}
        
        return {
            "status": "ingested",
            "last_ingestion_time": last.get("timestamp").isoformat(),
            "document_count": last.get("document_count"),
            "needs_refresh": self.should_refresh(),
        }
